"""empty message

Revision ID: 45b0a69ac16a
Revises: c3ae8da9779a
Create Date: 2026-02-22 14:48:41.604374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b0a69ac16a'
down_revision: Union[str, Sequence[str], None] = 'c3ae8da9779a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'is_active')
    # ### end Alembic commands ###
